# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('access_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('picture', models.FileField(upload_to=b'')),
                ('crooms', models.ManyToManyField(to='app.ChatRoom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('msg_type', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ChatRoom')),
            ],
        ),
    ]
